### ISSUE TITLE
Unable to compile class for JSP

### ISSUE THREAD

**Issue by BeingEasy** [zzhorc/tomcat_memshell_Listener_getandkill#1]
报错页面：
`HTTP Status 500 - Unable to compile class for JSP:

type Exception report

message Unable to compile class for JSP:

description The server encountered an internal error that prevented it from fulfilling this request.

exception

org.apache.jasper.JasperException: Unable to compile class for JSP: 

An error occurred at line: 351 in the jsp file: /tomcat-memshell-scanner-0.2.jsp
'<>' operator is not allowed for source level below 1.7
348:                     return;
349:                 }
350:                 out.write("<tbody>");
351:                 List<ServletRequestListener> newListeners = new ArrayList<>();
352:                 for (Object o : listeners) {
353:                     if (o instanceof ServletRequestListener) {
354:                         newListeners.add((ServletRequestListener) o);

Stacktrace:
	org.apache.jasper.compiler.DefaultErrorHandler.javacError(DefaultErrorHandler.java:103)
	org.apache.jasper.compiler.ErrorDispatcher.javacError(ErrorDispatcher.java:366)
	org.apache.jasper.compiler.JDTCompiler.generateClass(JDTCompiler.java:494)
	org.apache.jasper.compiler.Compiler.compile(Compiler.java:379)
	org.apache.jasper.compiler.Compiler.compile(Compiler.java:354)
	org.apache.jasper.compiler.Compiler.compile(Compiler.java:341)
	org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:662)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:364)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)

note The full stack trace of the root cause is available in the Apache Tomcat/7.0.76 logs.
Apache Tomcat/7.0.76`

jdk版本1.8.0
tomcat是在centos中使用yum install安装的直接启动的

**Comment by zzhorc** [comment]
'<>' operator is not allowed for source level below 1.7
tomcat7版本不兼容的语法符号 '<>'

**Comment by zzhorc** [comment]
> 报错页面： `HTTP Status 500 - Unable to compile class for JSP:
> 
> type Exception report
> 
> message Unable to compile class for JSP:
> 
> description The server encountered an internal error that prevented it from fulfilling this request.
> 
> exception
> 
> org.apache.jasper.JasperException: Unable to compile class for JSP:
> 
> An error occurred at line: 351 in the jsp file: /tomcat-memshell-scanner-0.2.jsp '<>' operator is not allowed for source level below 1.7 348: return; 349: } 350: out.write(""); 351: List newListeners = new ArrayList<>(); 352: for (Object o : listeners) { 353: if (o instanceof ServletRequestListener) { 354: newListeners.add((ServletRequestListener) o);
> 
> Stacktrace: org.apache.jasper.compiler.DefaultErrorHandler.javacError(DefaultErrorHandler.java:103) org.apache.jasper.compiler.ErrorDispatcher.javacError(ErrorDispatcher.java:366) org.apache.jasper.compiler.JDTCompiler.generateClass(JDTCompiler.java:494) org.apache.jasper.compiler.Compiler.compile(Compiler.java:379) org.apache.jasper.compiler.Compiler.compile(Compiler.java:354) org.apache.jasper.compiler.Compiler.compile(Compiler.java:341) org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:662) org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:364) org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395) org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339) javax.servlet.http.HttpServlet.service(HttpServlet.java:731) org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
> 
> note The full stack trace of the root cause is available in the Apache Tomcat/7.0.76 logs. Apache Tomcat/7.0.76`
> 
> jdk版本1.8.0 tomcat是在centos中使用yum install安装的直接启动的

试试这个 “List<Listener> newListeners = new ArrayList<Listener>();”

**Comment by zzhorc** [comment]
`List<ServletRequestListener> newListeners = new ArrayList<ServletRequestListener>();`
刚发现尖括号被过滤了，应该是试下这样
